### ISSUE TITLE
Warning Unexpected input(s) 'GITHUB_TOKEN' 

### ISSUE THREAD

**Issue by sorax** [Jaliborc/action-general-autotag#3]
GitHub Action shows warning when using `jaliborc/action-general-autotag@1.0.0` and `jaliborc/action-general-autotag@1.0.1`

`##[warning]Unexpected input(s) 'GITHUB_TOKEN', valid inputs are ['source_file', 'extraction_regex', 'tag_format', 'tag_message']
2
Run jaliborc/action-general-autotag@1.0.1
`

yml-file

```
[...]
steps:
      - uses: actions/checkout@master

      - uses: jaliborc/action-general-autotag@1.0.1
        id: autotag
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          source_file: "mix.exs"
          extraction_regex: "version:\\s\"([\\d\\.]+)\""
          tag_format: "v{version}"
[...]
```
